# ######### decohen-partners ##########
# Protein Ledger
"""Static assets shipped with the app.

A real package (rather than a bare directory) so ``importlib.resources`` can
find these after an install and inside the frozen binary, and so setuptools'
``packages.find`` picks it up without a separate declaration.

Contents:

- ``default_avatar.png`` — the default client avatar (GFP-47), regenerated by
  ``scripts/make_default_avatar.py``.
"""
