#!/usr/bin/env python
"""Regenerate db_script/schema_snapshot.txt (GFP-61).

The snapshot is a human-readable, diff-friendly description of the tables
and columns a brand-new database ends up with after db_script/init/ plus
every db_script/migration/ script is replayed against it, in order (see
db_script/README.md). It is committed to the repo specifically so that a
schema change shows up as an ordinary text diff in review, instead of only
being visible by reading a .ddl/.dml file and imagining the result.

tests/test_schema_guard.py asserts a freshly built database matches this
file exactly. If you change the schema (new migration under
db_script/migration/), regenerate this file in the SAME PR:

    .venv/Scripts/python.exe scripts/update_schema_snapshot.py

Pass --check to verify the committed file matches what db_script/ produces
without writing anything (exit 1 if it has drifted) -- this is what the test
suite does under the hood.
"""
from __future__ import annotations

import sqlite3
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT_PATH = ROOT / "db_script" / "schema_snapshot.txt"

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

HEADER = """\
# Auto-generated by scripts/update_schema_snapshot.py -- do not hand-edit.
# Regenerate: .venv/Scripts/python.exe scripts/update_schema_snapshot.py
#
# Tables and columns a brand-new database has once db_script/init/ and every
# db_script/migration/ script (see db_script/README.md) have been replayed
# against it, in order. schema_version itself is excluded -- it is app
# bookkeeping, not part of the application schema.
#
# Changing the schema requires updating this file in the same PR (GFP-61):
# that is the point -- a reviewer sees the structural diff here instead of
# it hiding inside a .ddl/.dml file.
"""


def _column_line(row: sqlite3.Row) -> str:
    """Render one PRAGMA table_info row as a stable, readable line."""
    parts = [row["type"] or ""]
    if row["notnull"]:
        parts.append("NOT NULL")
    if row["dflt_value"] is not None:
        parts.append(f"DEFAULT {row['dflt_value']}")
    if row["pk"]:
        parts.append("PK")
    return f"  {row['name']}: {' '.join(parts)}"


def build_snapshot() -> str:
    """Build a database purely from db_script/, then describe its structure.

    Deterministic: tables sorted by name, columns within a table sorted by
    name, so the output only changes when the schema actually does.
    """
    from grocery_planner import db

    with tempfile.TemporaryDirectory() as tmp:
        conn = db.connect(Path(tmp) / "snapshot.sqlite3")
        try:
            tables = [
                r["name"]
                for r in conn.execute(
                    "SELECT name FROM sqlite_master WHERE type='table' "
                    "AND name NOT IN ('schema_version', 'sqlite_sequence') "
                    "ORDER BY name"
                )
            ]
            lines = [HEADER]
            for table in tables:
                lines.append(f"TABLE {table}")
                cols = conn.execute(f"PRAGMA table_info({table})").fetchall()
                for row in sorted(cols, key=lambda r: r["name"]):
                    lines.append(_column_line(row))
                lines.append("")
            return "\n".join(lines).rstrip("\n") + "\n"
        finally:
            conn.close()


def main(argv: list[str]) -> int:
    check = "--check" in argv
    snapshot = build_snapshot()

    if check:
        current = SNAPSHOT_PATH.read_text(encoding="utf-8") if SNAPSHOT_PATH.exists() else ""
        if current != snapshot:
            print(f"{SNAPSHOT_PATH} is out of date with db_script/.")
            print("Regenerate it with:")
            print("  .venv/Scripts/python.exe scripts/update_schema_snapshot.py")
            return 1
        print(f"{SNAPSHOT_PATH} is up to date.")
        return 0

    SNAPSHOT_PATH.write_text(snapshot, encoding="utf-8")
    print(f"wrote {SNAPSHOT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
